import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path) => readFileSync(path, "utf8");
const protocol = read("plugins/android-daemon-native/src/main/java/com/gameplan/daemon/EyevueProtocol.kt");
const service = read("plugins/android-daemon-native/src/main/java/com/gameplan/daemon/EyevueGlassesService.kt");
const boot = read("plugins/android-daemon-native/src/main/java/com/gameplan/daemon/BootReceiver.kt");
const inference = read("plugins/android-daemon-native/src/main/java/com/gameplan/daemon/LocalGemmaInferenceEngine.kt");
const wake = read("plugins/android-daemon-native/src/main/java/com/gameplan/daemon/WakeWordService.kt");
const playback = read("plugins/android-daemon-native/src/main/java/com/gameplan/daemon/NativeTalkModePlaybackBridge.kt");
const generatedPlayback = read("android/app/src/main/java/com/gameplan/daemon/NativeTalkModePlaybackBridge.kt");
const manifest = read("android/app/src/main/AndroidManifest.xml");
const tool = read("server/agent/tools/daemon.ts");
const settings = read("components/androidDaemon/AndroidDeviceControlCard.tsx");
const eyevueSetup = read("lib/eyevue-setup.ts");
const bridge = read("server/daemon/bridge.ts");
const routes = read("server/routes.ts");
const nativeModule = read("plugins/android-daemon-native/src/main/java/com/gameplan/daemon/JarvisDaemonModule.kt");
const scanner = read("plugins/android-daemon-native/src/main/java/com/gameplan/daemon/EyevueDeviceScanner.kt");
const connectCard = read("components/eyevue/EyevueConnectCard.tsx");
const settingsScreen = read("app/(tabs)/settings.tsx");
const missionControl = read("app/(tabs)/index.tsx");
const jarvisChat = read("app/(tabs)/insights.tsx");
const approvalRisk = read("server/agent/approvalToolRisk.ts");
const coachConfirmation = read("server/routes/coachActionConfirmationRoutes.ts");
const approvalReceipt = read("server/agent/approvalReceipt.ts");
const agentApproval = read("server/agent/agentApproval.ts");
const coachAgent = read("server/channels/coachAgent.ts");
const outsideVoice = read("plugins/android-daemon-native/src/main/java/com/gameplan/daemon/OutsideAppVoiceSessionService.kt");

assert.match(protocol, /0000aa12-0000-1000-8000-00805f9b34fb/);
assert.match(protocol, /CMD_WAKE_START = 151/);
assert.match(protocol, /CMD_WAKE_END = 153/);
assert.match(protocol, /CMD_VOICE_DATA = 70/);
assert.match(protocol, /fun stopVendorVoice\(\)/);
assert.match(service, /hey,?\s*star/i);
assert.match(service, /CMD_WAKE_START -> \{[\s\S]*wakePacketsReceived = snapshot\.wakePacketsReceived \+ 1[\s\S]*lastWakePacketAt = System\.currentTimeMillis\(\)[\s\S]*beginWakeHandoff\(\)/);
assert.match(service, /ACTION_EXTERNAL_WAKE/);
assert.match(service, /ble_command_notify/);
assert.match(service, /stopVendorVoice\(\)[\s\S]*WebSocketService\.instance\?\.isConnected/);
assert.match(service, /SystemClock\.elapsedRealtime\(\)/);
assert.match(service, /onCharacteristicWrite[\s\S]*pendingWakeAfterStop[\s\S]*dispatchWakeEventNow/);
assert.match(service, /pendingWakeStopPacket\?\.contentEquals\(characteristic\.value\)/);
assert.match(service, /gatt !== callbackGatt/);
assert.match(service, /pendingWakeAfterStop\.set\(false\)/);
assert.match(wake, /ACTION_ARM_EXTERNAL/);
assert.match(nativeModule, /ACTION_ARM_EXTERNAL/);
assert.match(nativeModule, /RECORD_AUDIO[\s\S]*ACTION_ARM_EXTERNAL/);
assert.match(nativeModule, /fun armEyevueWake/);
assert.match(nativeModule, /wake: detected[\s\S]*\[redacted\]/);
assert.match(connectCard, /fullyReady = connected && microphoneReady && recognizerReady && voiceReady && wakeEvents > 0/);
assert.match(connectCard, /armEyevueWake/);
assert.match(connectCard, /next\.eyevueEnabled === true[\s\S]*microphonePermissionGranted/);
assert.match(service, /snapshot = snapshot\.copy\(wakeEvents = snapshot\.wakeEvents \+ 1, lastWakeAt = now\)/);
assert.match(service, /wakeEvents = 0,[\s\S]*lastWakeAt = null,[\s\S]*wakePacketsReceived = 0,[\s\S]*lastWakePacketAt = null/);
assert.match(boot, /ACTION_ARM_EXTERNAL/);
assert.match(wake, /ACTION_DISARM_EXTERNAL/);
assert.match(nativeModule, /WakeWordService\.disarmExternal\(\)/);
assert.match(service, /RECORD_AUDIO[\s\S]*armWake\(context\)/);
assert.match(wake, /fun disarmExternal/);
assert.match(connectCard, /deriveEyeVueVoiceReadiness/);
assert.match(connectCard, /voiceReady && wakeEvents > 0/);
assert.match(wake, /shutdownAfterExternalTalk/);
assert.match(wake, /ACTION_ARM_EXTERNAL[\s\S]*shutdownAfterExternalTalk = false/);
assert.match(connectCard, /title="Allow microphone and test wake" complete=\{wakeEvents > 0 && microphoneReady && recognizerReady && voiceReady\}/);
assert.match(connectCard, /eyeVueVoiceReadiness\.detail/);
assert.match(connectCard, /Allow microphone/);
assert.match(settings, /BLE wake bridge/);
assert.match(service, /Jarvis is offline\./);
assert.match(service, /pendingPhoto.*30, TimeUnit\.SECONDS/s);
assert.match(service, /percent <= 20/);
assert.match(service, /percent <= 10/);
assert.match(service, /temporary copy retained for active visual turn/);
assert.match(service, /requestedCapture == null[\s\S]*eyevue_photo_captured/);
assert.match(service, /requestedCapture\?\.timedOut\?\.get\(\) == true[\s\S]*discarded quarantined AA15 response/);
assert.match(service, /try \{[\s\S]*directory\.mkdirs\(\)[\s\S]*file\.writeBytes\(bytes\)[\s\S]*catch \(error: Throwable\)[\s\S]*requestedCapture\?\.failure\?\.set\(failure\)[\s\S]*requestedCapture\?\.latch\?\.countDown\(\)/);
assert.match(service, /catch \(error: Throwable\)[\s\S]*deleteFileWithRetry\(file\.absolutePath, "partial-cache-write"\)/);
assert.match(service, /PHOTO_LATE_RESPONSE_QUARANTINE_MS = 60_000L/);
assert.match(service, /synchronized\(gattStateLock\)[\s\S]*pendingPhoto\.get\(\) === photoRequest[\s\S]*photoRequest\.timedOut\.set\(true\)[\s\S]*closeConnection\(photoRequest\)[\s\S]*pendingPhoto\.compareAndSet\(photoRequest, null\)[\s\S]*PHOTO_LATE_RESPONSE_QUARANTINE_MS/);
assert.match(service, /!latch\.await\(30, TimeUnit\.SECONDS\)[\s\S]*photoRequest\?\.timedOut\?\.set\(true\)/);
assert.match(service, /gattStateLock = Any\(\)/);
assert.match(service, /onConnectionStateChange\(callbackGatt[\s\S]*synchronized\(gattStateLock\)[\s\S]*gatt !== callbackGatt[\s\S]*onServicesDiscovered\(callbackGatt[\s\S]*synchronized\(gattStateLock\)[\s\S]*gatt !== callbackGatt[\s\S]*onDescriptorWrite\(callbackGatt[\s\S]*synchronized\(gattStateLock\)[\s\S]*gatt !== callbackGatt/);
assert.match(service, /handleNotification\(callbackGatt[\s\S]*synchronized\(gattStateLock\)[\s\S]*gatt !== callbackGatt/);
assert.match(service, /photo = photoAssembler\.append\(value\)[\s\S]*pendingPhoto\.getAndSet\(null\)[\s\S]*photo\?\.let \{ saveCapturedPhoto\(it, requestedCapture\) \}/);
assert.match(service, /private fun closeConnection\(preservePendingPhoto:[\s\S]*abandonedPhoto !== preservePendingPhoto[\s\S]*EYEVUE_CONNECTION_LOST[\s\S]*latch\?\.countDown\(\)[\s\S]*gatt = null[\s\S]*decoder\.reset\(\)[\s\S]*photoAssembler\.reset\(\)/);
assert.match(protocol, /class EyevueFrameDecoder[\s\S]*fun reset\(\)[\s\S]*bytes\.reset\(\)/);
assert.match(protocol, /fun reset\(\)[\s\S]*active = false[\s\S]*image\.reset\(\)/);
assert.match(protocol, /MAX_PHOTO_BYTES = 20 \* 1024 \* 1024/);
assert.match(protocol, /chunkSize > maxPhotoBytes - image\.size\(\)[\s\S]*reset\(\)/);
assert.match(service, /val takeNew = op\.optBoolean\("lookAgain", false\)/);
assert.doesNotMatch(service, /lookAgain[\s\S]{0,100}\|\|[\s\S]{0,100}lastPhotoPath/);
assert.match(service, /status != BluetoothGatt\.GATT_SUCCESS[\s\S]*failGattSetup/);
assert.match(service, /fun start\([\s\S]*hasBluetoothPermission\(context\)[\s\S]*return false/);
assert.match(service, /ACCESS_FINE_LOCATION/);
assert.match(service, /scheduleTemporaryPhotoExpiry\(file\.absolutePath, origin\)/);
assert.doesNotMatch(service, /lastPhotoPath\?\.let \{ old -> deleteFileWithRetry\(old, "replacement"\) \}/);
assert.match(service, /targetPath = expectedPath \?: currentPath[\s\S]*targetFile\.parentFile != allowedDirectory[\s\S]*targetFile\.delete\(\)/);
assert.match(service, /boundImagePath = op\.optString\("imagePath"[\s\S]*boundFile\.parentFile != allowedDirectory \|\| !boundFile\.isFile[\s\S]*boundFile\.absolutePath/);
assert.match(service, /TEMPORARY_PHOTO_TTL_MS/);
assert.match(service, /fun start\([\s\S]*purgeTemporaryPhotos\(context, "pre_service_start"\)[\s\S]*hasBluetoothPermission\(context\)/);
assert.match(service, /onCreate\(\)[\s\S]*purgeTemporaryPhotos\(this, "service_start"\)/);
assert.match(boot, /purgeTemporaryPhotos\(context, "boot"\)[\s\S]*EyevueGlassesService\.start\(context\)/);
assert.match(service, /!targetFile\.exists\(\) \|\| targetFile\.delete\(\)[\s\S]*if \(!deleted\)[\s\S]*return false/);
assert.match(wake, /ACTION_EXTERNAL_WAKE/);
assert.match(wake, /ACTION_EXTERNAL_WAKE[\s\S]*enteringTalkMode[\s\S]*destroyRecognizer\(\)[\s\S]*startListening\(\)/);
assert.match(inference, /Content\.ImageFile/);
assert.match(inference, /15_000L/);
assert.match(inference, /30_000L/);
assert.match(inference, /visionDeadlineAtElapsedMs[\s\S]*remainingMs[\s\S]*future\.get\(remainingMs, TimeUnit\.MILLISECONDS\)/);
assert.match(inference, /quarantineTimedOutNativeAttempt/);
assert.match(inference, /catch \(_: TimeoutException\)[\s\S]*quarantineTimedOutNativeAttempt[\s\S]*active\.job\.cancel\(\)/);
assert.match(inference, /acquireEngineForRequest[\s\S]*engineOwnershipLock[\s\S]*claimEngineForQuarantineLocked/);
assert.match(inference, /cachedEngine = engineState\?\.engine[\s\S]*engineState = null[\s\S]*claimEngineForQuarantineLocked/);
assert.match(inference, /return engineLock\.withLock \{[\s\S]*val lockedCurrent = engineState[\s\S]*onEngineCreated\(lockedCurrent\.engine\)/);
assert.doesNotMatch(inference, /val current = engineState[\s\S]{0,500}return engineLock\.withLock/);
assert.match(inference, /claimEngineForSynchronousClose\(failedEngine\)[\s\S]*failedEngine\.close\(\)/);
assert.match(inference, /quarantinedEngines\.any \{ it === engine \}/);
assert.match(inference, /commitEngineStateForRequest[\s\S]*deadlineExceeded[\s\S]*engineState = state/);
assert.match(inference, /releaseEngineForGeneration\(active, imagePaths\.isNotEmpty\(\), throwOnDeadline = true\)/);
assert.match(inference, /future\.get\(remainingMs, TimeUnit\.MILLISECONDS\)[\s\S]*closeEngineAsync/);
assert.match(inference, /closeTimedOut[\s\S]*active\.engine = null[\s\S]*executor\.shutdown\(\)/);
assert.doesNotMatch(inference, /catch \(_: TimeoutException\)[\s\S]{0,500}future\.cancel\(true\)[\s\S]{0,500}closeEngineAsync/);
assert.doesNotMatch(inference, /catch \(e: LocalGemmaDeadlineExceededException\)[\s\S]{0,200}\.close\(\)/);
assert.match(inference, /catch \(e: Throwable\)[\s\S]*abortRequested\(\)[\s\S]*LocalGemmaDeadlineExceededException/);
assert.match(inference, /conversation\.cancelProcess\(\)/);
assert.match(inference, /stalledEngines\.forEach \{ closeEngineAsync\(it, active\.requestId\) \}/);
assert.match(inference, /warmEngineReleaseRequested\.set\(true\)[\s\S]*releaseWarmEngineIfIdle\(\)/);
assert.match(inference, /operationAdmission\.releaseGeneration\(requestId\)[\s\S]*releaseWarmEngineIfIdle\(\)/);
assert.match(inference, /visionBackend/);
assert.match(manifest, /BLUETOOTH_SCAN/);
assert.match(manifest, /foregroundServiceType="connectedDevice"/);
assert.match(tool, /android_eyevue_look/);
assert.match(tool, /set lookAgain=true; that new capture requires durable user approval/);
assert.match(approvalRisk, /EYEVUE_CAPTURE_COMMANDS = new Set\(\["photo", "video_start", "audio_start"\]\)/);
assert.match(approvalRisk, /android_eyevue_look" && toolArgs\?\.lookAgain === true\) return `\$\{action\}:lookAgain`/);
assert.match(approvalRisk, /android_eyevue_command[\s\S]*EYEVUE_CAPTURE_COMMANDS/);
assert.match(approvalRisk, /isEyevueCaptureAction[\s\S]*eyevueCaptureApprovalText\(toolName, toolArgs\) !== undefined/);
assert.match(tool, /isEyevueCaptureAction\("daemon_action", args\)[\s\S]*approvalReceiptCoversToolCall/);
assert.match(tool, /originalUserText: eyevueCaptureApprovalText\("daemon_action", args\)/);
assert.match(approvalReceipt, /call\.originalUserText && call\.originalUserText !== receipt\.originalUserText/);
assert.match(routes, /eyeVueCaptureApprovalRequired = isEyevueCaptureAction[\s\S]*eyeVueCaptureApprovalRequired \|\|[\s\S]*pendingConfirmations\.set/);
assert.doesNotMatch(routes, /durableApprovalGateId|durableApprovalExpiresAtMs/);
assert.match(coachConfirmation, /isEyevueCaptureAction\(pending\.tool, pending\.args\)[\s\S]*requestApproval\([\s\S]*suppressDeliverable: true[\s\S]*approveGate\(createdGate\.id, userId\)[\s\S]*createApprovalReceipt\([\s\S]*expiresAt: gate\.expiresAt/);
assert.match(agentApproval, /gt\(agentApprovalGates\.expiresAt, now\)/);
assert.match(agentApproval, /!autoApprove && !req\.suppressDeliverable/);
assert.match(coachConfirmation, /gate\?\.userId !== userId \|\| gate\.status !== "approved" \|\| gate\.expiresAt\.getTime\(\) <= Date\.now\(\)/);
assert.match(settings, /eyeVue Companion/);
assert.match(connectCard, /eyevuePermissionGranted !== true[\s\S]*requestEyevuePermissions/);
assert.match(settings, /deriveEyeVueVoiceReadiness\(\{/);
assert.match(settings, /nativeRecognitionReady = eyeVueVoiceReadiness\.nativeRecognitionReady/);
assert.match(settings, /wearableAudioDeviceName: nativeSpeechStatus\?\.wearableAudioDeviceName/);
assert.match(settings, /eyevueDeviceName: status\?\.eyevueDeviceName/);
assert.match(eyevueSetup, /eyeVueAudioEndpointMatches[\s\S]*eyevue === audio/);
assert.match(eyevueSetup, /ready =[\s\S]*wearableAudioAvailable === true[\s\S]*endpointMatches/);
assert.match(nativeModule, /reactApplicationContext\.currentActivity/);
assert.match(nativeModule, /Build\.VERSION\.SDK_INT >= Build\.VERSION_CODES\.S[\s\S]*ACCESS_FINE_LOCATION/);
assert.match(nativeModule, /fun scanEyevueDevices[\s\S]*EyevueDeviceScanner\.scan/);
assert.match(nativeModule, /E_EYEVUE_SELECTION_REQUIRED/);
assert.match(scanner, /Discovery intentionally returns every named or bonded device/);
assert.match(scanner, /adapter\.bondedDevices\.forEach/);
assert.match(scanner, /scanner\.startScan\(callback\)/);
assert.doesNotMatch(service, /isEyevue\(name/);
assert.doesNotMatch(service, /bondedDevices\.firstOrNull/);
assert.match(service, /No glasses selected[\s\S]*choose the device you want to use/);
assert.match(service, /private fun rejectSelectedDevice\(message: String\) \{[\s\S]*WakeWordService\.disarmExternal\(\)/);
assert.match(service, /device\.createBond\(\)/);
assert.match(service, /currentAddress != address[\s\S]*closeConnection\(\)[\s\S]*connecting\.set\(false\)/);
assert.match(service, /status != BluetoothGatt\.GATT_SUCCESS[\s\S]*service discovery failed[\s\S]*failGattSetup/);
assert.match(connectCard, /scanAndroidEyevueDevices/);
assert.match(connectCard, /devices\.map\(device/);
assert.match(connectCard, /enableAndroidEyevue\(device\.address\)/);
assert.match(connectCard, /disconnectAndroidEyevue\(\)[\s\S]*enableAndroidEyevue\(device\.address\)/);
assert.match(connectCard, /Open Android assistant settings/);
assert.match(connectCard, /not required for EYE VUE’s BLE wake event/);
assert.match(connectCard, /assistantActive/);
assert.match(settingsScreen, /Jarvis OS Device Control[\s\S]*<EyevueConnectCard \/>/);
assert.doesNotMatch(missionControl, /EyevueConnectCard/);
assert.doesNotMatch(jarvisChat, /EyevueConnectCard/);
assert.match(bridge, /android_eyevue_discard_photo/);
assert.doesNotMatch(bridge, /processDaemonUtterance\([\s\S]{0,700}\.finally\(async \(\) =>[\s\S]{0,700}android_eyevue_discard_photo/);
assert.match(bridge, /capturedImagePath[\s\S]*eyeVueCapturedImagePath: capturedImagePath/);
assert.match(outsideVoice, /endSession\(\)[\s\S]*EyevueGlassesService\.discardTemporaryPhoto\(\)/);
assert.match(service, /TEMPORARY_PHOTO_TTL_MS = 5 \* 60_000L[\s\S]*scheduleTemporaryPhotoExpiry\(file\.absolutePath, origin\)/);
assert.match(tool, /action === "android_eyevue_command"[\s\S]*"photo"[\s\S]*"video_start"[\s\S]*"audio_start"[\s\S]*\? "android_camera"[\s\S]*: null/);
assert.match(bridge, /op\.type === "android_eyevue_command"[\s\S]*op\.command === "photo"[\s\S]*op\.command === "video_start"[\s\S]*op\.command === "audio_start"[\s\S]*\? "android_camera"[\s\S]*: null/);
assert.doesNotMatch(bridge, /android_eyevue_(?:status|disconnect):\s*"android_camera"/);
assert.match(bridge, /m\.type === "eyevue_vision_delay"[\s\S]*type: "notify"[\s\S]*Jarvis local vision/);
assert.match(tool, /ctx\.state\.eyeVueCapturedImagePath[\s\S]*imagePath: boundImagePath/);
assert.match(coachAgent, /eyeVueCapturedImagePath: input\.eyeVueCapturedImagePath/);
assert.equal(playback, generatedPlayback, "NativeTalkModePlaybackBridge.kt must stay mirrored between plugin and generated Android trees");
assert.match(playback, /WEARABLE_PLAYBACK_RECOVERY_TIMEOUT_MS = 10_000L/);
assert.match(playback, /waitForWearableRoute[\s\S]*route\.active[\s\S]*System\.currentTimeMillis\(\) >= deadlineMs/);
assert.match(playback, /could not restore the glasses speaker within 10 seconds/);
assert.match(playback, /cancelWearableRouteCheck\(\)[\s\S]*WearableAudioRouteManager\.release/);
assert.match(playback, /if \(!initialRoute\.available\)[\s\S]*ensureTts/);
assert.match(playback, /monitorWearableRoute[\s\S]*!route\.active[\s\S]*tts\?\.stop\(\)[\s\S]*waitForWearableRoute/);

for (const name of ["BootReceiver.kt", "EyevueProtocol.kt", "EyevueGlassesService.kt", "EyevueDeviceScanner.kt", "LocalGemmaInferenceEngine.kt"]) {
  assert.equal(
    read(`plugins/android-daemon-native/src/main/java/com/gameplan/daemon/${name}`),
    read(`android/app/src/main/java/com/gameplan/daemon/${name}`),
    `${name} must remain identical in the Expo template and generated Android tree`,
  );
}

console.log("OK: eyeVue local-first glasses integration contract is wired");
